const DEF={title:'Get Key LQM iOS',logo:'https://play-lh.googleusercontent.com/Vcxb9Q-GG4Md6c9uCMCRnDlx8DUpiXgAnO7HXkSQTJKjV1MxLr5hZZVCf6nSfX8OsAc',taskHeading:'Nhiệm vụ',unlockHeading:'Mở khoá key',accent:'#178ee8',accent2:'#5577ff',tasks:[],unlocks:[],guides:[]};
const $=s=>document.querySelector(s);const load=()=>{try{return {...DEF,...JSON.parse(localStorage.getItem('getkey_config')||'{}')}}catch{return {...DEF}}};let cfg=load();
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function auth(){return sessionStorage.getItem('getkey_admin_auth')==='1'}function showApp(){if(auth())$('#login').style.display='none'}showApp();$('#loginForm').onsubmit=e=>{e.preventDefault();const p=localStorage.getItem('getkey_admin_password')||'admin123';if($('#password').value===p){sessionStorage.setItem('getkey_admin_auth','1');$('#login').style.display='none'}else toast('Sai mật khẩu')};
function field(id,val){$('#'+id).value=val??''}function render(){field('title',cfg.title);field('logo',cfg.logo);field('taskHeading',cfg.taskHeading);field('unlockHeading',cfg.unlockHeading);field('accent',cfg.accent);field('accent2',cfg.accent2);renderTasks();renderSimple('unlocks');renderSimple('guides')}
function renderTasks(){$('#tasks').innerHTML=cfg.tasks.map((t,i)=>`<div class="item" draggable="true" data-type="tasks" data-index="${i}"><div class="drag">☰</div><div class="row"><input class="mini" data-k="title" value="${esc(t.title)}" placeholder="Tên nhiệm vụ"><input class="mini" data-k="url" value="${esc(t.url)}" placeholder="Link"><input class="mini" data-k="icon" value="${esc(t.icon)}" placeholder="URL icon"><input class="mini" data-k="bg" type="color" value="${esc(t.bg||'#555555')}"><button class="remove">Xoá</button></div></div>`).join('')}
function renderSimple(type){$('#'+type).innerHTML=cfg[type].map((x,i)=>`<div class="item" draggable="true" data-type="${type}" data-index="${i}"><div class="drag">☰</div><div class="row simple"><input class="mini" data-k="title" value="${esc(x.title)}" placeholder="Tên hiển thị"><input class="mini" data-k="url" value="${esc(x.url)}" placeholder="Link"><button class="remove">Xoá</button></div></div>`).join('')}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.addEventListener('input',e=>{const item=e.target.closest('.item');if(!item||!e.target.dataset.k)return;cfg[item.dataset.type][+item.dataset.index][e.target.dataset.k]=e.target.value});document.addEventListener('click',e=>{if(e.target.matches('.remove')){const item=e.target.closest('.item'),type=item.dataset.type;cfg[type].splice(+item.dataset.index,1);type==='tasks'?renderTasks():renderSimple(type)}if(e.target.dataset.add==='task'){cfg.tasks.push({id:'task_'+Date.now(),title:'Nhiệm vụ mới',url:'#',icon:'https://cdn.simpleicons.org/linktree/ffffff',bg:'#5577ff'});renderTasks()}if(e.target.dataset.add==='unlock'){cfg.unlocks.push({title:'Link mới',url:'#'});renderSimple('unlocks')}if(e.target.dataset.add==='guide'){cfg.guides.push({title:'Hướng dẫn mới',url:'#'});renderSimple('guides')}});
let drag=null;document.addEventListener('dragstart',e=>{const i=e.target.closest('.item');if(i)drag={type:i.dataset.type,index:+i.dataset.index}});document.addEventListener('dragover',e=>{if(e.target.closest('.item'))e.preventDefault()});document.addEventListener('drop',e=>{const i=e.target.closest('.item');if(!i||!drag||i.dataset.type!==drag.type)return;const to=+i.dataset.index,[m]=cfg[drag.type].splice(drag.index,1);cfg[drag.type].splice(to,0,m);drag.type==='tasks'?renderTasks():renderSimple(drag.type);drag=null});
$('#saveBtn').onclick=()=>{cfg.title=$('#title').value.trim()||DEF.title;cfg.logo=$('#logo').value.trim()||DEF.logo;cfg.taskHeading=$('#taskHeading').value.trim()||'Nhiệm vụ';cfg.unlockHeading=$('#unlockHeading').value.trim()||'Mở khoá key';cfg.accent=$('#accent').value;cfg.accent2=$('#accent2').value;const np=$('#newPassword').value;if(np){if(np.length<4)return toast('Mật khẩu tối thiểu 4 ký tự');localStorage.setItem('getkey_admin_password',np);$('#newPassword').value=''}localStorage.setItem('getkey_config',JSON.stringify(cfg));toast('Đã lưu')};
$('#resetProgress').onclick=()=>{if(confirm('Xoá toàn bộ tiến độ nhiệm vụ?')){localStorage.removeItem('getkey_completed');toast('Đã xoá tiến độ')}};$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(cfg,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='getkey-config.json';a.click();URL.revokeObjectURL(a.href)};$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{try{const j=JSON.parse(await e.target.files[0].text());cfg={...DEF,...j};render();toast('Đã nhập, bấm Lưu')}catch{toast('File JSON không hợp lệ')}};render();
